# Generated by Django 4.2.3 on 2023-07-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='lord', max_length=88),
        ),
    ]
